In [5]:
#ARRAYS
import numpy as np


In [6]:
#NUMPY(Numerical Python)

In [7]:
x=[0,1,2,3,4]
for i in x:
   print(i/2)

0.0
0.5
1.0
1.5
2.0


In [8]:
x=np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [9]:
x/2

array([1., 2., 3., 4., 5.])

In [10]:
type(x)

numpy.ndarray

In [11]:
#numpy has a rich set of numpy function

#set 1 : random functions : used to develope random arrays

In [12]:
import numpy as np
np.random.randint(0,10,6)

array([8, 7, 3, 7, 1, 9], dtype=int32)

In [13]:
array = np.random.randint(0,10,(3,3))
print (array)

[[2 1 8]
 [9 4 7]
 [1 5 9]]


In [14]:
array = np.random.randint(0,10,(2,5))
array

array([[5, 1, 2, 7, 3],
       [1, 4, 0, 7, 5]], dtype=int32)

In [15]:
np.random.rand(10)

array([0.23518931, 0.28929691, 0.06285804, 0.48296313, 0.21761564,
       0.63250261, 0.3539076 , 0.8789264 , 0.60539362, 0.84631012])

In [16]:
np.random.rand(2)

array([0.83437207, 0.16285983])

In [17]:
#NUMPY SLICING

In [18]:
data = np.random.randint(0,10,(5,4))
data

array([[7, 1, 7, 8],
       [2, 3, 2, 2],
       [8, 9, 3, 0],
       [5, 5, 9, 3],
       [8, 2, 3, 5]], dtype=int32)

In [19]:
data[1:,:2]

array([[2, 3],
       [8, 9],
       [5, 5],
       [8, 2]], dtype=int32)

In [20]:
data[2:4,1:]

array([[9, 3, 0],
       [5, 9, 3]], dtype=int32)

In [21]:
data.sum() # it will show the sum of all numbers present in the data array

np.int64(92)

In [22]:
data.max()        # it will show the max number that is present in the data array

np.int32(9)

In [23]:
data.min()        # it will show the min number that is present in the data array

np.int32(0)

In [24]:
# 1D Array

In [25]:
a = np.array([4,8,11])
print(a)

[ 4  8 11]


In [26]:
# 2D Array

In [27]:
b = np.array([[4,8,11],[16,45,1]])
print(b)

[[ 4  8 11]
 [16 45  1]]


In [28]:
# 3D Array

In [29]:
m1 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[8,8,7]]])
print(m1)
type(m1)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [8 8 7]]]


numpy.ndarray

In [30]:
#Initialize numpy arrays

In [31]:
# initialize x X y dimentions with ' 0 ' values

In [32]:
# if we want all ' 0 's then zeros() will be used

In [33]:
np.zeros((4,2))   #initializing numpy array which have all the values ' 0 ' .

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
# if we want all ' 1 's then ones() will be used

In [35]:
np.ones((4,2))   #initializing numpy array which have all the values ' 1 ' .

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
# in case we want some other values except 0 & 1 then full() will be used

In [37]:
np.full((5,3),-3)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [38]:
# initialize 'x' and 'y' with an interval of 'z'

In [39]:
# if we want numbers from x to y in the interval of 5 we use arange()

In [40]:
np.arange(0,101,5)    #it will show the numbers from 0 to 101 in the interval of 5 

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [41]:
np.arange(0,20)       #it will show the numbers from 0 to 20, by default it will take interval of 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
# initialize z numbers between x and y

# divide upper and lower limit to equal measures

In [43]:
np.linspace(5,10,4)

array([ 5.        ,  6.66666667,  8.33333333, 10.        ])

In [44]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [45]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [46]:
# identical matrix

In [47]:
np.eye(5)     # here i will get the identical matrix i.e having 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
np.eye(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#ndarray.shape                     #it will shows howmany rows and howmany columns are there

In [51]:
print(m1.shape)                    #.shape will shows howmany rows and howmany columns are there

(2, 2, 3)


In [52]:
# we can use ndarray.shape to resize the array

In [53]:
a = np.array([[2,4,6,5],[1,9,11,6],[6,7,10,1]])
print("original array : \n", a)
a.shape = (6,2)
print("resized array : \n", a)

original array : 
 [[ 2  4  6  5]
 [ 1  9 11  6]
 [ 6  7 10  1]]
resized array : 
 [[ 2  4]
 [ 6  5]
 [ 1  9]
 [11  6]
 [ 6  7]
 [10  1]]


In [54]:
z = np.arange(24)
print(z)
# if i want to make a 3D array from the given array then 
z.shape = (6,2,2) #6 * 2 * 2 = 24, or we can use 4,3,2
print(z)
print(z.ndim)      #ndim refers how many dimentions are in the array, here 3D

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]
3


In [55]:
z = np.arange(30)
z.shape = (2,5,3)
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [56]:
z = np.arange(30)
z.shape = (3,10)
print(z)
print(z.ndim)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
2


In [57]:
d = np.arange(24,dtype='float')   # if we won't mention dtype then it will take dtype = int
print(d)                                  # if we want float dtype then we have to mention dtype = float 


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


In [82]:
a = np.array([[1,2,3],[4,5,6],[5,8,12]])
print(f"size : {a.size}")
print(f"shape : {a.shape}")
print(f"no.of dimentions : {a.ndim}")
print(f"datatype : {a.dtype}")

size : 9
shape : (3, 3)
no.of dimentions : 2
datatype : int64


In [58]:
x = np.random.randint(0,20,(6,5))
print(x)
print(x.shape)

[[ 7  7  6  7  7]
 [ 7 12  0  1  3]
 [ 0 14 13  0 13]
 [13 14 19  9  0]
 [13 10  1  3 19]
 [18  9 11  7  9]]
(6, 5)


In [85]:
x.shape()

TypeError: 'tuple' object is not callable

In [ ]:
x.shape   #shape tool gives a tuple of array dimention 
          #and can be used to change the dimention of an array

(6, 5)

In [ ]:
x.reshape(10,3)     #reshape tool gives a new shape to an array
                    #without changing its data

array([[ 7,  7,  6],
       [ 7,  7,  7],
       [12,  0,  1],
       [ 3,  0, 14],
       [13,  0, 13],
       [13, 14, 19],
       [ 9,  0, 13],
       [10,  1,  3],
       [19, 18,  9],
       [11,  7,  9]], dtype=int32)

In [79]:
x.ravel()

array([ 7,  7,  6,  7,  7,  7, 12,  0,  1,  3,  0, 14, 13,  0, 13, 13, 14,
       19,  9,  0, 13, 10,  1,  3, 19, 18,  9, 11,  7,  9], dtype=int32)

In [81]:
y = x.ravel()
y

array([ 7,  7,  6,  7,  7,  7, 12,  0,  1,  3,  0, 14, 13,  0, 13, 13, 14,
       19,  9,  0, 13, 10,  1,  3, 19, 18,  9, 11,  7,  9], dtype=int32)

In [60]:
x1 = np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [61]:
x2 = np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [62]:
np.vstack([x1,x2])     #vertical stacking

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [63]:
np.hstack([x1,x2])     #horizontal stacking

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [64]:
np.concatenate([x1,x2],axis=0)     #vertical stacking

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [65]:
np.concatenate([x1,x2],axis=1)      #horizontal stacking

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [66]:
a = [10,20]
b = [20,5]
np.sum([a,b])

np.int64(55)

In [67]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
sum_arrays = arr1 + arr2
print(f"addithon:\n{sum_arrays}")

addithon:
[[ 8 10 12]
 [14 16 18]]


In [68]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
arr3 = np.array([[8,6,9],
                 [10,9,13]])
sum_arrays = arr1 + arr2 + arr3
print(f"addithon:\n{sum_arrays}")

addithon:
[[16 16 21]
 [24 25 31]]


In [69]:
np.subtract(10,8)

np.int64(2)

In [70]:
arr1 = np.array([[10,20,30],
                [40,50,60]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
#arr3 = np.array([[8,6,9],
                 #[10,9,13]])
subtract_arrays = arr1 - arr2
print(f"subtraction:\n{subtract_arrays}")

subtraction:
[[ 3 12 21]
 [30 39 48]]


In [71]:
arr1 = np.array([[10,20,30],
                [40,50,60]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])
arr3 = np.array([[8,6,9],
                 [10,9,13]])
subtract_arrays = arr1 - arr2 - arr3
print(f"subtraction:\n{subtract_arrays}")

subtraction:
[[-5  6 12]
 [20 30 35]]


In [84]:
#broadcasting (using different shapes)
a = np.array([[1,2],[6,8]])
b = np.array([5,4])

# addition from each row of 'a' using broadcasing
result = a + b
print(f"result of a + b with broadcasting : \n {result}")


result of a + b with broadcasting : 
 [[ 6  6]
 [11 12]]
