# NUMPY
   is a powerful library for numerical computations in Python.
    It provides support for arrays, matrices, and
    many mathematical functions to operate on these data structures.

In [6]:
#to get the division of all elements we have to iterate it using for loop
x =[2,4,6,8,10]
for i in x:
  print(i/2)

1.0
2.0
3.0
4.0
5.0


In [7]:
x/2 #here we cannot use as the above code is iterated in a particular block

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
# So to make it happen and get the code easier we will use the NUMPY module

In [ ]:
import numpy as np
x=np.array([2,4,6,8,10])

print(x) 

[ 2  4  6  8 10]


In [ ]:
x*2 #as we have used the numpy module we can call the variable and can do any calculation in it

array([ 4,  8, 12, 16, 20])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
#Numpy has Rich set of NumPy Functions:

## Set1 = Random Functions:

In [ ]:
import numpy as np
np.random.randint(0,10,6)   #randint will generate randopm integer numbers in range of 0 t0 10 , the number of elements it will print is 6

array([7, 9, 7, 0, 9, 0], dtype=int32)

In [ ]:
array=np.random.randint(0,10,(3,4)) # range is 1 to 10 and (3,4) is the no. of rows and columns i.e, it will generate a 3x4 matrix
array

array([[1, 7, 4, 0],
       [2, 5, 4, 2],
       [2, 6, 8, 5]], dtype=int32)

In [ ]:
np.random.randint(0,10,(2,3)) 

array([[4, 6, 8],
       [9, 2, 2]], dtype=int32)

In [ ]:
np.random.randint(100,200,2) #it will generate random 2 numbers from 100 to 200

array([168, 173], dtype=int32)

In [ ]:
#Numpy slicing
array[1: ,0:2]

array([[2, 5],
       [2, 6]], dtype=int32)

In [ ]:
data = np.random.randint(0,10,(5,4))
data

array([[3, 8, 9, 5],
       [4, 1, 5, 0],
       [0, 1, 7, 2],
       [3, 8, 5, 5],
       [4, 4, 1, 5]], dtype=int32)

In [ ]:
data[1: , :2]

array([[4, 1],
       [0, 1],
       [3, 8],
       [4, 4]], dtype=int32)

In [ ]:
data[2:4,1: ]

array([[1, 7, 2],
       [8, 5, 5]], dtype=int32)

In [ ]:
#Numpy

#1 D array:

import numpy as np
a=np.array([1,23,24])
print(a)

[ 1 23 24]


In [ ]:
import numpy as np

#1D array
a =np.array([2,3,4])
print(a)
np.ndim(a)

[2 3 4]


1

In [ ]:
#2D array

b=np.array([[2,4,6],[8,10,12],[5,6,7]])
print(b)
np.ndim(b)

[[ 2  4  6]
 [ 8 10 12]
 [ 5  6  7]]


2

In [ ]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # <-3 dim
print(d)
np.ndim(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [ ]:
a= np.array([1,2,3]) #--> 1 dim
b=np.array([[1,2,3],[4,5,6]]) #--> 2 dim
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #--> 3 dim
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))

1
2
3


In [ ]:
#Initialize Numpy arrays

#initialize 'x X y' dimensions with '0' values
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
import numpy as np

#full array with -6 values
np.full((4,4),-6)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

In [ ]:
#1D Array

a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2d array
a =np.array([[2,4,6],[4,5,6],[6,5,7]])

print(a)
print(type(a))
a.ndim

[[2 4 6]
 [4 5 6]
 [6 5 7]]
<class 'numpy.ndarray'>


2

In [ ]:
#3d array
x= np.array([[[1,2,3], [4,5,6],[5,6,7]], [[4,5,6],[8,8,7],[8,9,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[4 5 6]
  [8 8 7]
  [8 9 7]]]
<class 'numpy.ndarray'>


3

In [ ]:
#Initilize 'x' and 'y' with an interval of z

np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
#initialize 'z' numbers between 'x' and 'y'
#devide upper and lower limit to equal measures

np.linspace(0,20,5)


array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(5)  # eye: refer to identical matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np

# Create the NumPy array
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

# Print the array
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [ ]:
dt =[1,3,4]
sum(dt)

8

In [ ]:
data.max()

np.int64(12)

In [ ]:
data.mean()

np.float64(6.0)

In [ ]:
data.sum()

np.int64(120)

In [ ]:
#Fill SAME numbers in an array of dimensions 'x' X 'y'

np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
#ndarray.shape:

a=np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


In [ ]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)   #2,3

(2, 3)


In [ ]:
#We can use ndarray.shape function to resize the array:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]]) #3,4 =12
print("Original Array:\n", a)
a.shape=(6,2)   #12 = 1,2,3,4,6,12 (1,12), (2,6),(3,4),(4,3),(6,2)(12,1)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
# 12= 1*12,2*6,3*4, 4*3,6*2,1*12
b.shape=(1,12)  
print("1*12:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(2,6)  
print("2*6:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(3,4)  
print("3*4:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(4,3)  
print("4*3:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(6,2)  
print("6*2:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)

1*12:
 [[1 2 3 4 5 6 5 8 8 5 6 4]]
Size of the array:  12
Dimension of the array 2


2*6:
 [[1 2 3 4 5 6]
 [5 8 8 5 6 4]]
Size of the array:  12
Dimension of the array 2


3*4:
 [[1 2 3 4]
 [5 6 5 8]
 [8 5 6 4]]
Size of the array:  12
Dimension of the array 2


4*3:
 [[1 2 3]
 [4 5 6]
 [5 8 8]
 [5 6 4]]
Size of the array:  12
Dimension of the array 2


6*2:
 [[1 2]
 [3 4]
 [5 6]
 [5 8]
 [8 5]
 [6 4]]
Size of the array:  12
Dimension of the array 2


In [ ]:
z=np.arange(24)
print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,6,2) (4,2,3)
z.shape=(2,3,4)  #4,3,2
#3 dimensional
print(z)
print(z.ndim)  #.ndim= no of dimenssions in that array
print("\n")
z.shape=(4,2,3)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [ ]:
z=np.arange(30)
#print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,5,3),(3,5,2),(1,10,3)
z.shape=(1,10,3)  #2,2,2,3
#3 dimensional
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [ ]:
Y =np.arange(200)  #0,1,.......,199
#print(Y)
#print(Y.size)    #200 =100*2 =50*2*2=25*2*2*2=5*5*2*2*2


Y.shape=(4,2,5,5) #5*5*4*2
print(Y)
print(Y.ndim)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]
   [ 20  21  22  23  24]]

  [[ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]
   [ 40  41  42  43  44]
   [ 45  46  47  48  49]]]


 [[[ 50  51  52  53  54]
   [ 55  56  57  58  59]
   [ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]]

  [[ 75  76  77  78  79]
   [ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]]


 [[[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]
   [120 121 122 123 124]]

  [[125 126 127 128 129]
   [130 131 132 133 134]
   [135 136 137 138 139]
   [140 141 142 143 144]
   [145 146 147 148 149]]]


 [[[150 151 152 153 154]
   [155 156 157 158 159]
   [160 161 162 163 164]
   [165 166 167 168 169]
   [170 171 172 173 174]]

  [[175 176 177 178 179]
   [180 181 182 183 184]
   [185 186 187 188 189]
   [190 191 192 193 194]
   [1

In [11]:
import numpy as np
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)
print(b.ndim)
#Convert above array into 2D and 3D array
#2D
b.shape=(3,2)
print(b)#6=1,2,3,6
print(b.ndim)
#3D
b.shape=(1,2,3)
print(b)
print(b.ndim)

(2, 3)
2
[[ 4  5]
 [ 6  6]
 [ 8 10]]
2
[[[ 4  5  6]
  [ 6  8 10]]]
3


# Find the number elements in array

In [12]:
import numpy as np

In [13]:
a= np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size )   
print(a.shape)   
print(a.ndim)
print(a.dtype)

9
(3, 3)
2
int64


In [14]:
a=np.array([
    [[1,2,3,4],[4,5,6,8]],
     [[7,8,9,4],[4,5,5,6]]
])
print(a.size)
print(a.dtype)

import numpy as np

print(a.shape)
print(a.ndim)

16
int64
(2, 2, 4)
3


In [21]:
import numpy as np

x=np.random.randint(0,20,(6,5))
print(x)

[[ 9  2 18  3 10]
 [19 17 10  8  5]
 [14  6 19  8  7]
 [ 1 14  5  3 13]
 [10 13 13 14  0]
 [ 1 13  8  5  2]]


In [ ]:
# x.shape=(2,15)
# print(x)

[[13  1 10 17  1  3  1  5 16 14 19 19  9  1 13]
 [ 6 18  9  0 16 18  6 18 17  8  6  9  6 17 15]]


The shape and reshape functions in NumPy serve different purposes related to array dimensions:
- **Shape**
1) shape is an attribute of a NumPy array that returns a tuple representing the dimensions of the array.
2) It is used to get the current shape of an array. 
3) It can also be used to modify the shape of the array in-place by assigning a new tuple of dimensions, but this is less common and can be error-prone.
4) It does not create a new array but rather provides information about the existing array or modifies it directly.
- **Reshape**
1) reshape is a function that changes the shape of a NumPy array without changing its data.
2) It returns a new array with the specified shape, provided that the new shape is compatible with the original array size (i.e., the number of elements remains the same).
3) It does not modify the original array unless assigned back to it.
4) It is commonly used to transform arrays into different dimensions for various operations.

In [22]:
x.ravel() #ravel flattens the array

array([ 9,  2, 18,  3, 10, 19, 17, 10,  8,  5, 14,  6, 19,  8,  7,  1, 14,
        5,  3, 13, 10, 13, 13, 14,  0,  1, 13,  8,  5,  2], dtype=int32)

In [23]:
x.reshape(3,10)

array([[ 9,  2, 18,  3, 10, 19, 17, 10,  8,  5],
       [14,  6, 19,  8,  7,  1, 14,  5,  3, 13],
       [10, 13, 13, 14,  0,  1, 13,  8,  5,  2]], dtype=int32)

In [25]:
print(x) #so reshape doesnt change values/ dimension the original array is unchanged

[[ 9  2 18  3 10]
 [19 17 10  8  5]
 [14  6 19  8  7]
 [ 1 14  5  3 13]
 [10 13 13 14  0]
 [ 1 13  8  5  2]]


In [26]:
x.reshape(10,3)

array([[ 9,  2, 18],
       [ 3, 10, 19],
       [17, 10,  8],
       [ 5, 14,  6],
       [19,  8,  7],
       [ 1, 14,  5],
       [ 3, 13, 10],
       [13, 13, 14],
       [ 0,  1, 13],
       [ 8,  5,  2]], dtype=int32)

In [27]:
print(x)

[[ 9  2 18  3 10]
 [19 17 10  8  5]
 [14  6 19  8  7]
 [ 1 14  5  3 13]
 [10 13 13 14  0]
 [ 1 13  8  5  2]]


In [28]:
x.reshape(5,6)

array([[ 9,  2, 18,  3, 10, 19],
       [17, 10,  8,  5, 14,  6],
       [19,  8,  7,  1, 14,  5],
       [ 3, 13, 10, 13, 13, 14],
       [ 0,  1, 13,  8,  5,  2]], dtype=int32)

In [29]:
print(x)

[[ 9  2 18  3 10]
 [19 17 10  8  5]
 [14  6 19  8  7]
 [ 1 14  5  3 13]
 [10 13 13 14  0]
 [ 1 13  8  5  2]]


In [30]:
x1 =np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [31]:
x2= np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [32]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [33]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [40]:
np.concatenate([x1,x2],axis=0)  #vstack axis = 0 --> row

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [41]:
np.concatenate([x1,x2],axis=1)   #hstack axis = 1 --> column

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [42]:
x=np.random.randint(0,10,(4,6))
x

array([[1, 4, 5, 5, 2, 9],
       [4, 6, 2, 6, 2, 0],
       [8, 4, 3, 2, 5, 7],
       [7, 0, 8, 3, 8, 7]], dtype=int32)

In [39]:
np.split(x,2,axis=0)

[array([[6, 6, 9, 7, 8, 8],
        [6, 2, 7, 7, 7, 3]], dtype=int32),
 array([[1, 2, 1, 4, 0, 9],
        [7, 8, 9, 0, 2, 6]], dtype=int32)]

In [43]:
np.split(x,2,axis=1)

[array([[1, 4, 5],
        [4, 6, 2],
        [8, 4, 3],
        [7, 0, 8]], dtype=int32),
 array([[5, 2, 9],
        [6, 2, 0],
        [2, 5, 7],
        [3, 8, 7]], dtype=int32)]

# finding the data type of an array

In [44]:
d=np.arange(24)  #[0,-----,23]
print(d)
print(d.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
int64


In [45]:
d=np.arange(24,dtype='float') #0,1,.....,23
print(d)
print(d.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
float64


# Numpy array Mathematical - SUM

In [46]:
import numpy as np
np.sum([10,30,60,54,68,258])

np.int64(480)

In [47]:
a=[10,20]   #25+30
b=[20,5]

np.sum([a,b])

np.int64(55)

In [48]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],       #[8,10,12],[14,16,18]
                   [10, 11, 12]])

array3 = np.array([[8, 6, 9],      #[16,16,21],[24,25,31]
                   [10, 9, 13]])

# Adding the two arrays
sum_array = array1+array2+array3
print("Addition:\n", sum_array)
sum_array.ndim

Addition:
 [[16 16 21]
 [24 25 31]]


2

# SUBTRACTION

In [49]:
import numpy as np

np.subtract(10,20)

np.int64(-10)

In [50]:
#Subtraction of two arrays:

a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])
Sub = a-b-c
print(Sub)

[ 0 -5  1]


In [51]:
a=[0,1]
b=[0,5]

np.subtract(a,b)

array([ 0, -4])

In [53]:
import numpy as np

a = np.array([[2, 4],
              [5,8]])
b = np.array([[4, 6],
              [3,5]])

# Perform element-wise subtraction
result = np.subtract(a, b)
print("Result of a - b: \n", result)

Result of a - b: 
 [[-2 -2]
 [ 2  3]]


Broadcasting in NumPy enables arithmetic operations between arrays with different shapes, provided they are compatible. NumPy automatically "stretches" the smaller array to match the shape of the larger array, without creating copies of the data. This allows for efficient element-wise operations.

In [54]:
#Using Different Shapes(Broadcasting)
import numpy as np

a = np.array([[1, 2],
              [6, 8],
              [6, 5]])
b = np.array([5,4])

# Addition from each row of a using broadcasting
result = a + b
print("Result of a + b with broadcasting:\n", result)

Result of a + b with broadcasting:
 [[ 6  6]
 [11 12]
 [11  9]]


In [55]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Subtracting the second array from the first array
difference_array = array1 - array2
print("Subtraction:\n", difference_array)

Subtraction:
 [[ 9 18 27]
 [36 45 54]]


In [56]:
import numpy as np

a = np.array([1, 2, 3])      # Shape (3,)
b = np.array([[4], [5]])    # Shape (2, 1)

result = a + b  
print(result)

[[5 6 7]
 [6 7 8]]


# Multiplication of numpy array

In [57]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [59]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([7, 8, 9])

product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16 27]
 [28 40 54]]


In [58]:
array1 = np.array([[1, 2,3],
                   [4, 5,3],
                   [4,6,1]])

array2 = np.array([[7, 8],
                  [4,1],
                   [5,2]
                   ])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

# Matrix Multiplication
the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix. The product of matrices A and B is denoted as AB.

In [63]:
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))
print(x1)
print(x2)

[[8 7]
 [2 1]]
[[4 5]
 [9 9]]


In [64]:
np.dot(x1,x2)

array([[ 95, 103],
       [ 17,  19]], dtype=int32)

In [68]:
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(3,2))
print(x1)
print(x2)

[[5 8 3]
 [0 3 5]]
[[3 6]
 [3 9]
 [4 0]]


In [69]:
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(2,2))
print(x1)
print(x2)
#it will show error as no. of elements in each matrix should be equal i.e, m*n = p*k

[[0 3 2]
 [3 1 7]]
[[5 5]
 [4 3]]


In [67]:
np.dot(x1,x2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

# Datatypes in numpy
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

# String Functions

In [71]:
x=np.array([1,2,3,'data'])
x

array(['1', '2', '3', 'data'], dtype='<U21')

In [72]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U21')

In [75]:
np.char.center(x,10,fillchar='-')

array(['----1-----', '----2-----', '----3-----', '---data---'],
      dtype='<U10')

In [76]:
x=np.array([1,2,3,'data eNginEerIng'])
x

array(['1', '2', '3', 'data eNginEerIng'], dtype='<U21')

In [77]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']


In [78]:
np.char.split(x)

array([list(['1']), list(['2']), list(['3']),
       list(['data', 'eNginEerIng'])], dtype=object)

In [80]:
y=np.array(["Data Science","Machine Learning"])
y

array(['Data Science', 'Machine Learning'], dtype='<U16')

In [81]:
np.char.split(y,sep='e')

array([list(['Data Sci', 'nc', '']), list(['Machin', ' L', 'arning'])],
      dtype=object)

In [82]:
np.char.count(y,"i")

array([1, 2])

In [83]:
y

array(['Data Science', 'Machine Learning'], dtype='<U16')

In [84]:
np.char.startswith(y, "M")

array([False,  True])

In [85]:
np.char.replace(y,'a','xxxxxxx')

array(['Dxxxxxxxtxxxxxxx Science', 'Mxxxxxxxchine Lexxxxxxxrning'],
      dtype='<U28')

In [86]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [87]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

# Time Base Functions:
- YYYY:MM:DD  HH:MM:SS  Time Stamp
- YYYY:MM:DD   Date
- HH:MM:SS      Time

# Purpose:
- extract month and identify
- can be found answers questions based on time series
- extracting yeras, week, days, studied

# Division of arrays

In [88]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[3, 4, 5],
                   [10, 5, 3]])

# Dividing the first array by the second array element-wise
division_array = array1 / array2
print("Division:\n", division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


# Calculating the exponential
This line calculates the exponential of each element in the array a.
The function np.exp() applies the exponential function
𝑒^a
  to each element in the array.

In [89]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 2, 3, 4, 5])

# Calculating the exponential of each element in the array
exp_a = np.exp(a)

print("Original array:", a)
print("Exponential of the array:", exp_a)  #e = 2.718281828459045

Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [90]:
import math
math.e

2.718281828459045

In [91]:
#Exponential of a 2D Array


import numpy as np

# Creating a 2D NumPy array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Calculating the exponential of each element in the 2D array
exp_b = np.exp(b)

print("Original 2D array:\n", b)
print("Exponential of the 2D array:\n", exp_b)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Exponential of the 2D array:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


# Square Root (np.sqrt())
The np.sqrt() function computes the non-negative square root of each element in the input array.

In [92]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 4, 9, 16, 25,37])

# Calculating the square root of each element
sqrt_a = np.sqrt(a)

print("Original array:", a)  #[1,4,9,16,25]
print("Square root of the array:", sqrt_a)  #[1.,2.,3.,4.,5.]

Original array: [ 1  4  9 16 25 37]
Square root of the array: [1.         2.         3.         4.         5.         6.08276253]


In [93]:
#expo, sqrt,sin,cos,log

a=np.array([2,4,6])

print("sqrt of a:", np.sqrt(a))
print("exp of a:", np.exp(a))
print("sin of a:", np.sin(a))
print("cos of a:", np.cos(a))
print("log of a:", np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
exp of a: [  7.3890561   54.59815003 403.42879349]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


In [ ]:
#Aggregate Functions:

#aggregate functions perform computations on arrays to return a single value.
#Here are some common aggregate functions in NumPy

a=np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))   # 42
print("Minimum Value:", np.min(a))   #1
print("Maxmum Value:", np.max(a))
print("Mean Value:", np.mean(a))     #mean =average
print("Median Value:", np.median(a)) #
print("Corelation Coefficient:", np.corrcoef(a))   #
print("Standard Deviation:", np.std(a))

Sum: 42
Minimum Value: 1
Maxmum Value: 9
Mean Value: 5.25
Median Value: 5.5
Corelation Coefficient: 1.0
Standard Deviation: 2.6339134382131846
