# NUMPY
   is a powerful library for numerical computations in Python.
    It provides support for arrays, matrices, and
    many mathematical functions to operate on these data structures.

In [ ]:
#to get the division of all elements we have to iterate it using for loop
x =[2,4,6,8,10]
for i in x:
  print(i/2)

1.0
2.0
3.0
4.0
5.0


In [3]:
x/2 #here we cannot use as the above code is iterated in a particular block

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
# So to make it happen and get the code easier we will use the NUMPY module

In [ ]:
import numpy as np
x=np.array([2,4,6,8,10])

print(x) 

[ 2  4  6  8 10]


In [6]:
x*2 #as we have used the numpy module we can call the variable and can do any calculation in it

array([ 4,  8, 12, 16, 20])

In [7]:
type(x)

numpy.ndarray

In [8]:
#Numpy has Rich set of NumPy Functions:

## Set1 = Random Functions:

In [14]:
import numpy as np
np.random.randint(0,10,6)   #randint will generate randopm integer numbers in range of 0 t0 10 , the number of elements it will print is 6

array([7, 9, 7, 0, 9, 0], dtype=int32)

In [18]:
array=np.random.randint(0,10,(3,4)) # range is 1 to 10 and (3,4) is the no. of rows and columns i.e, it will generate a 3x4 matrix
array

array([[1, 7, 4, 0],
       [2, 5, 4, 2],
       [2, 6, 8, 5]], dtype=int32)

In [17]:
np.random.randint(0,10,(2,3)) 

array([[4, 6, 8],
       [9, 2, 2]], dtype=int32)

In [21]:
np.random.randint(100,200,2) #it will generate random 2 numbers from 100 to 200

array([168, 173], dtype=int32)

In [22]:
#Numpy slicing
array[1: ,0:2]

array([[2, 5],
       [2, 6]], dtype=int32)

In [24]:
data = np.random.randint(0,10,(5,4))
data

array([[3, 8, 9, 5],
       [4, 1, 5, 0],
       [0, 1, 7, 2],
       [3, 8, 5, 5],
       [4, 4, 1, 5]], dtype=int32)

In [25]:
data[1: , :2]

array([[4, 1],
       [0, 1],
       [3, 8],
       [4, 4]], dtype=int32)

In [26]:
data[2:4,1: ]

array([[1, 7, 2],
       [8, 5, 5]], dtype=int32)

In [28]:
#Numpy

#1 D array:

import numpy as np
a=np.array([1,23,24])
print(a)

[ 1 23 24]


In [36]:
import numpy as np

#1D array
a =np.array([2,3,4])
print(a)
np.ndim(a)

[2 3 4]


1

In [37]:
#2D array

b=np.array([[2,4,6],[8,10,12],[5,6,7]])
print(b)
np.ndim(b)

[[ 2  4  6]
 [ 8 10 12]
 [ 5  6  7]]


2

In [41]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # <-3 dim
print(d)
np.ndim(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [45]:
a= np.array([1,2,3]) #--> 1 dim
b=np.array([[1,2,3],[4,5,6]]) #--> 2 dim
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #--> 3 dim
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))

1
2
3


In [46]:
#Initialize Numpy arrays

#initialize 'x X y' dimensions with '0' values
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
import numpy as np

#full array with -6 values
np.full((4,4),-6)

array([[-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6],
       [-6, -6, -6, -6]])

In [51]:
#1D Array

a=np.array([1,2,3])
print(a)

[1 2 3]


In [52]:
#2d array
a =np.array([[2,4,6],[4,5,6],[6,5,7]])

print(a)
print(type(a))
a.ndim

[[2 4 6]
 [4 5 6]
 [6 5 7]]
<class 'numpy.ndarray'>


2

In [54]:
#3d array
x= np.array([[[1,2,3], [4,5,6],[5,6,7]], [[4,5,6],[8,8,7],[8,9,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[4 5 6]
  [8 8 7]
  [8 9 7]]]
<class 'numpy.ndarray'>


3

In [55]:
#Initilize 'x' and 'y' with an interval of z

np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [56]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [57]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
#initialize 'z' numbers between 'x' and 'y'
#devide upper and lower limit to equal measures

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [59]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [60]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [61]:
np.eye(5)  # eye: refer to identical matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [64]:
import numpy as np

# Create the NumPy array
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

# Print the array
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [65]:
dt =[1,3,4]
sum(dt)

8

In [66]:
data.max()

np.int64(12)

In [67]:
data.mean()

np.float64(6.0)

In [68]:
data.sum()

np.int64(120)

In [69]:
#Fill SAME numbers in an array of dimensions 'x' X 'y'

np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [70]:
#ndarray.shape:

a=np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


In [71]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)   #2,3

(2, 3)


In [72]:
#We can use ndarray.shape function to resize the array:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]]) #3,4 =12
print("Original Array:\n", a)
a.shape=(6,2)   #12 = 1,2,3,4,6,12 (1,12), (2,6),(3,4),(4,3),(6,2)(12,1)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [77]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
# 12= 1*12,2*6,3*4, 4*3,6*2,1*12
b.shape=(1,12)  
print("1*12:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(2,6)  
print("2*6:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(3,4)  
print("3*4:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(4,3)  
print("4*3:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)
print("\n")
b.shape=(6,2)  
print("6*2:\n",b)
print("Size of the array: ",b.size)
print("Dimension of the array",b.ndim)

1*12:
 [[1 2 3 4 5 6 5 8 8 5 6 4]]
Size of the array:  12
Dimension of the array 2


2*6:
 [[1 2 3 4 5 6]
 [5 8 8 5 6 4]]
Size of the array:  12
Dimension of the array 2


3*4:
 [[1 2 3 4]
 [5 6 5 8]
 [8 5 6 4]]
Size of the array:  12
Dimension of the array 2


4*3:
 [[1 2 3]
 [4 5 6]
 [5 8 8]
 [5 6 4]]
Size of the array:  12
Dimension of the array 2


6*2:
 [[1 2]
 [3 4]
 [5 6]
 [5 8]
 [8 5]
 [6 4]]
Size of the array:  12
Dimension of the array 2
